"""Add payment and outbox models

Revision ID: c951d4174a2c
Revises: d237a83ddef5
Create Date: 2026-04-22 00:47:41.514281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c951d4174a2c'
down_revision: Union[str, Sequence[str], None] = 'd237a83ddef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('aggregate_id', sa.UUID(), nullable=False),
                    sa.Column('event_type', sa.String(length=100), nullable=False),
                    sa.Column('payload', sa.JSON(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('retry_count', sa.Integer(), nullable=False),
                    sa.Column('last_error', sa.String(length=500), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('processed_at', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__outbox'))
                    )
    op.create_index(op.f('ix__outbox__aggregate_id'), 'outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix__outbox__created_at'), 'outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix__outbox__status'), 'outbox', ['status'], unique=False)
    op.create_index('ix_outbox_aggregate_type', 'outbox', ['aggregate_id', 'event_type'], unique=False)
    op.create_index('ix_outbox_pending', 'outbox', ['status', 'created_at'], unique=False)
    op.create_table('payments',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
                    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
                    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('payment_metadata', sa.JSON(), nullable=True),
                    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='paymentstatus'),
                              nullable=False),
                    sa.Column('webhook_url', sa.String(length=500), nullable=False),
                    sa.Column('processed_at', sa.DateTime(), nullable=True),
                    sa.Column('error_message', sa.String(length=1000), nullable=True),
                    sa.Column('retry_count', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.CheckConstraint('amount > 0', name=op.f('ck__payments__check_amount_positive')),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__payments'))
                    )
    op.create_index(op.f('ix__payments__idempotency_key'), 'payments', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix__payments__status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_status_created', table_name='payments')
    op.drop_index(op.f('ix__payments__status'), table_name='payments')
    op.drop_index(op.f('ix__payments__idempotency_key'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_outbox_pending', table_name='outbox')
    op.drop_index('ix_outbox_aggregate_type', table_name='outbox')
    op.drop_index(op.f('ix__outbox__status'), table_name='outbox')
    op.drop_index(op.f('ix__outbox__created_at'), table_name='outbox')
    op.drop_index(op.f('ix__outbox__aggregate_id'), table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
